services:
  booru:
    container_name: testbed
    build: .
    ports:
      - 8000:8000
    restart: unless-stopped
    tty: true
    depends_on:  
      - db
    environment:
      - INSTALL_DSN=pgsql:user=admin;password=pass;host=db;dbname=postdb
    volumes:
      - /mnt/hoard/shimmie/data:/app/data

  db:
    container_name: testdb
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postdb
    volumes:
      - /mnt/hoard/shimmie/postgres_data:/var/lib/postgresql/data
